USE citizenConnect
GO
CREATE TABLE PDFs (
    PDFID VARCHAR (255) PRIMARY KEY,
    OfficialID VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserID),
    Title NVARCHAR(255) NOT NULL,
    PDFUrl NVARCHAR(255) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
)
GO
