USE citizenConnect
GO
CREATE TABLE Views (
    ViewID VARCHAR(255) PRIMARY KEY,
    UserID VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES Users(UserID),
    Title NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
)
GO

SELECT * FROM Views;